language: php
env:
  - OC_ROOT=/home/travis/build/fercamp09/opencart-test-suite/www/
php:
  - "5.4"
install:
  composer install
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
script:
  - bin/robo travis:opencart-setup
  - bin/phpunit --testsuite catalog-tests
  - bin/phpunit --testsuite admin-tests